spring:
  thymeleaf:
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
    cache: false
  freemarker:
    template-loader-path: classpath:/templates/freemarker
  mvc:
    favicon:
      enabled: false
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true